import type { Metadata } from "next";
import { Anybody as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "./providers";
import Header from "@/components/navigation/header";

const sans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body className={cn("relative antialiased font-sans", sans.variable)}>
        <Providers>
          <div className="relative container min-h-dvh flex flex-col">
            <Header />
            <main className="flex-1 pt-10">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
